
FROM node:14.9 as build

WORKDIR /fronted

ENV PATH /fronted/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install --silent

RUN npm install react-scripts@3.4.3 -g --silent

COPY . . 

RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /fronted/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]