apiVersion: apps/v1
kind: Deployment
metadata:
  name: redismessage
  namespace: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redismessage
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: redismessage
    spec:
      containers:
      - name: redispub-container
        image: dani3l8200/redispub
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: redissub-container
        imagePullPolicy: Always
        image: dani3l8200/redissub
---
apiVersion: v1
kind: Service
metadata:
  name: redismessage
  namespace: project
spec:
  selector:
    app: redismessage
  ports:
    - name: service
      port: 80

