apiVersion: v1
kind: Service
metadata:
  name: service-redis
  namespace: project
  labels:
    app: app-redis
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6075
  selector:
    app: app-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-redis
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-redis
  template:
    metadata:
      labels:
        app: app-redis
    spec:
      containers:
        - name: redis-pub
          image: gcr.io/proyecto2-sopes1-313601/redispub
          ports:
          - containerPort: 6075
            protocol: TCP
        - name: redis-sub
          image: gcr.io/proyecto2-sopes1-313601/redissub
          ports:
            - containerPort: 3000
              protocol: TCP
